USE master
GO

CREATE DATABASE JXGL8 ON
( NAME = JXGL_data8,
FILENAME = 'C:\JXGL8.mdf',
SIZE = 5MB, 
MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = JXGL_log8, 
FILENAME = 'C:\JXGL_log8.ldf', 
SIZE = 5MB,
MAXSIZE = UNLIMITED, FILEGROWTH = 10%);
