// Generated by gencpp from file opencv_apps/FaceRecognitionTrain.msg
// DO NOT EDIT!


#ifndef OPENCV_APPS_MESSAGE_FACERECOGNITIONTRAIN_H
#define OPENCV_APPS_MESSAGE_FACERECOGNITIONTRAIN_H

#include <ros/service_traits.h>


#include <opencv_apps/FaceRecognitionTrainRequest.h>
#include <opencv_apps/FaceRecognitionTrainResponse.h>


namespace opencv_apps
{

struct FaceRecognitionTrain
{

typedef FaceRecognitionTrainRequest Request;
typedef FaceRecognitionTrainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FaceRecognitionTrain
} // namespace opencv_apps


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opencv_apps::FaceRecognitionTrain > {
  static const char* value()
  {
    return "c47a3ceb75cbe248d69217439e66a8e2";
  }

  static const char* value(const ::opencv_apps::FaceRecognitionTrain&) { return value(); }
};

template<>
struct DataType< ::opencv_apps::FaceRecognitionTrain > {
  static const char* value()
  {
    return "opencv_apps/FaceRecognitionTrain";
  }

  static const char* value(const ::opencv_apps::FaceRecognitionTrain&) { return value(); }
};


// service_traits::MD5Sum< ::opencv_apps::FaceRecognitionTrainRequest> should match
// service_traits::MD5Sum< ::opencv_apps::FaceRecognitionTrain >
template<>
struct MD5Sum< ::opencv_apps::FaceRecognitionTrainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_apps::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::opencv_apps::FaceRecognitionTrainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_apps::FaceRecognitionTrainRequest> should match
// service_traits::DataType< ::opencv_apps::FaceRecognitionTrain >
template<>
struct DataType< ::opencv_apps::FaceRecognitionTrainRequest>
{
  static const char* value()
  {
    return DataType< ::opencv_apps::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::opencv_apps::FaceRecognitionTrainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opencv_apps::FaceRecognitionTrainResponse> should match
// service_traits::MD5Sum< ::opencv_apps::FaceRecognitionTrain >
template<>
struct MD5Sum< ::opencv_apps::FaceRecognitionTrainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_apps::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::opencv_apps::FaceRecognitionTrainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_apps::FaceRecognitionTrainResponse> should match
// service_traits::DataType< ::opencv_apps::FaceRecognitionTrain >
template<>
struct DataType< ::opencv_apps::FaceRecognitionTrainResponse>
{
  static const char* value()
  {
    return DataType< ::opencv_apps::FaceRecognitionTrain >::value();
  }
  static const char* value(const ::opencv_apps::FaceRecognitionTrainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENCV_APPS_MESSAGE_FACERECOGNITIONTRAIN_H
