USE master
GO

CREATE DATABASE JXGL7 ON
( NAME = JXGL_data7,
FILENAME = 'D:\SQLdata\JXGL7.mdf',
SIZE = 5MB, 
MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = JXGL_log7, 
FILENAME = 'D:\SQLdata\JXGL_log7.ldf', 
SIZE = 5MB,
MAXSIZE = UNLIMITED, FILEGROWTH = 10%);
