(cl:defpackage opencv_apps-srv
  (:use )
  (:export
   "FACERECOGNITIONTRAIN"
   "<FACERECOGNITIONTRAIN-REQUEST>"
   "FACERECOGNITIONTRAIN-REQUEST"
   "<FACERECOGNITIONTRAIN-RESPONSE>"
   "FACERECOGNITIONTRAIN-RESPONSE"
  ))

