/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "value.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0         (GUI_ID_USER + 0x00)
#define ID_BUTTON_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_1         (GUI_ID_USER + 0x02)
#define ID_BUTTON_2         (GUI_ID_USER + 0x03)
#define ID_BUTTON_3         (GUI_ID_USER + 0x04)
#define ID_BUTTON_4         (GUI_ID_USER + 0x05)
#define ID_BUTTON_5         (GUI_ID_USER + 0x06)
#define ID_BUTTON_6         (GUI_ID_USER + 0x07)
#define ID_BUTTON_7         (GUI_ID_USER + 0x08)
#define ID_BUTTON_8         (GUI_ID_USER + 0x09)
#define ID_BUTTON_9         (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10         (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11         (GUI_ID_USER + 0x0C)
#define ID_EDIT_0         (GUI_ID_USER + 0x0E)
#define ID_TEXT_0         (GUI_ID_USER + 0x0F)

#define ID_IMAGE_0        (GUI_ID_USER + 0x10)
#define ID_IMAGE_0_IMAGE_0     0x00
extern const U8 _acImage_0[391734];
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
#define plen 8 //密码长度
// USER START (Optionally insert additional static data)
// USER END
u8 closeP=0; 
char BUFFER[5];
u8 PBUF[plen+1],pl=0;
u8 pword[]="12345678";//201603 090324
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Set Threshold", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 0x64, 0 },
{ IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 480, 272, 0, 0, 0 },	//img @@@@@@@@@@@@@@@@@@@@@@@@@@@@
  { BUTTON_CreateIndirect, "0", ID_BUTTON_0, 205, 185, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_1, 125, 50, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_2, 205, 50, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_3, 285, 50, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_4, 125, 95, 70, 34, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_5, 205, 95, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_6, 285, 95, 70, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_7, 125, 140, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_8, 205, 140, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_9, 285, 140, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Del", ID_BUTTON_10, 125, 185, 70, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_11, 285, 185, 70, 35, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 125, 10, 230, 28, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Error", ID_TEXT_0, 364, 17, 80, 20, 0, 0x0, 0 },//
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  }
  return NULL;
}
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;//img @@@@@@@@@@@@@@@@@@@@@@@@@@@@
	U32          FileSize;//img @@@@@@@@@@@@@@@@@@@@@@@@@@@@
	WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Input password'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
	 //
    // Initialization of 'Image'//img @@@@@@@@@@@@@@@@@@@@@@@@@@@@
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    IMAGE_SetBMP(hItem, pData, FileSize);
    //
    // Initialization of '0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of '9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of 'Del'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of 'OK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Error'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem,"");		
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
      if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='0';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
				      
				      
			}
        break; 
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='1';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
							
			}
        break; 
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='2';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
        if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='3';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='4';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
        if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='5';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='6';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='7';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='8';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
         if(pl<plen)//输入长度小于最大限定长度
			{
		        	PBUF[pl++]='9';//赋值后 数据长度加1
	            PBUF[pl]=0;//添加结束符
			}
        break; 
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Del'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
          if(pl>0)// 长度 大于0  才可以进行删除
					{
						 if(closeP==2)closeP=3;//清除error显示标志
						  
						 PBUF[--pl]=0;//向前移动一位 添加结束符
					}
        break; 
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED: 
        break;
      case WM_NOTIFICATION_RELEASED:
				closeP=1;
        break; 
      }
      break;
    
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateInput password
*/

WM_HWIN CreateInputFramewin(void) 
{
  WM_HWIN hWin,hItem;
  u8 Tp=0;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	closeP =0; 
  PBUF[0]=0;
	pl=0;
	
	while(1)
	{
		int i=0;
		  if(Tp!=pl)//字符长度有变化 刷新数据
			{
			   hItem = WM_GetDialogItem(hWin, ID_EDIT_0); 
			   EDIT_SetText(hItem,(void*)PBUF);
			} 
			if(closeP==3)//error清除显示
			{
         hItem = WM_GetDialogItem(hWin, ID_TEXT_0); 
			   TEXT_SetText(hItem,(void*)"");		
         closeP=0;				
			}
	    else if(closeP==2)
			{
			   hItem = WM_GetDialogItem(hWin, ID_TEXT_0); 
			   TEXT_SetText(hItem,(void*)"Error");	
			}
	    else if(closeP==1)
				
			{
				
				DataInfo.Atemp=0;
				for( i=0;i<pl;i++){
				     DataInfo.Atemp=DataInfo.Atemp*10+PBUF[i]-'0';
				}
				DataInfo.Avalue[DataInfo.DtypeSel]=DataInfo.Atemp; 
				AT24CXX_Write(adrr+DataInfo.DtypeSel*2,(u8*)&DataInfo.Avalue[DataInfo.DtypeSel],2) ;//????
				hItem = WM_GetDialogItem(hWin, ID_TEXT_0);
			  WM_DeleteWindow(hWin);//删除窗体 
				
	      return 0;
			}
	  GUI_Delay(100); 
	}
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
