// Generated by gencpp from file learning_server/IntPlusRequest.msg
// DO NOT EDIT!


#ifndef LEARNING_SERVER_MESSAGE_INTPLUSREQUEST_H
#define LEARNING_SERVER_MESSAGE_INTPLUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_server
{
template <class ContainerAllocator>
struct IntPlusRequest_
{
  typedef IntPlusRequest_<ContainerAllocator> Type;

  IntPlusRequest_()
    : a(0)
    , b(0)  {
    }
  IntPlusRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef uint8_t _a_type;
  _a_type a;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::learning_server::IntPlusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_server::IntPlusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IntPlusRequest_

typedef ::learning_server::IntPlusRequest_<std::allocator<void> > IntPlusRequest;

typedef boost::shared_ptr< ::learning_server::IntPlusRequest > IntPlusRequestPtr;
typedef boost::shared_ptr< ::learning_server::IntPlusRequest const> IntPlusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_server::IntPlusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_server::IntPlusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_server::IntPlusRequest_<ContainerAllocator1> & lhs, const ::learning_server::IntPlusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_server::IntPlusRequest_<ContainerAllocator1> & lhs, const ::learning_server::IntPlusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_server::IntPlusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_server::IntPlusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_server::IntPlusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_server::IntPlusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_server::IntPlusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_server::IntPlusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_server::IntPlusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbc791ad747ce9f10dc3c89e6698b08a";
  }

  static const char* value(const ::learning_server::IntPlusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbc791ad747ce9f1ULL;
  static const uint64_t static_value2 = 0x0dc3c89e6698b08aULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_server::IntPlusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_server/IntPlusRequest";
  }

  static const char* value(const ::learning_server::IntPlusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_server::IntPlusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  a\n"
"uint8  b\n"
"\n"
;
  }

  static const char* value(const ::learning_server::IntPlusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_server::IntPlusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntPlusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_server::IntPlusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_server::IntPlusRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_SERVER_MESSAGE_INTPLUSREQUEST_H
