// Generated by gencpp from file transbot_msgs/BuzzerRequest.msg
// DO NOT EDIT!


#ifndef TRANSBOT_MSGS_MESSAGE_BUZZERREQUEST_H
#define TRANSBOT_MSGS_MESSAGE_BUZZERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transbot_msgs
{
template <class ContainerAllocator>
struct BuzzerRequest_
{
  typedef BuzzerRequest_<ContainerAllocator> Type;

  BuzzerRequest_()
    : buzzer(0)  {
    }
  BuzzerRequest_(const ContainerAllocator& _alloc)
    : buzzer(0)  {
  (void)_alloc;
    }



   typedef int32_t _buzzer_type;
  _buzzer_type buzzer;





  typedef boost::shared_ptr< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BuzzerRequest_

typedef ::transbot_msgs::BuzzerRequest_<std::allocator<void> > BuzzerRequest;

typedef boost::shared_ptr< ::transbot_msgs::BuzzerRequest > BuzzerRequestPtr;
typedef boost::shared_ptr< ::transbot_msgs::BuzzerRequest const> BuzzerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transbot_msgs::BuzzerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transbot_msgs::BuzzerRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::BuzzerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.buzzer == rhs.buzzer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transbot_msgs::BuzzerRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::BuzzerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "130d26476a79b1e0eb57138986019cf0";
  }

  static const char* value(const ::transbot_msgs::BuzzerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x130d26476a79b1e0ULL;
  static const uint64_t static_value2 = 0xeb57138986019cf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transbot_msgs/BuzzerRequest";
  }

  static const char* value(const ::transbot_msgs::BuzzerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 buzzer\n"
;
  }

  static const char* value(const ::transbot_msgs::BuzzerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.buzzer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BuzzerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transbot_msgs::BuzzerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transbot_msgs::BuzzerRequest_<ContainerAllocator>& v)
  {
    s << indent << "buzzer: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buzzer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSBOT_MSGS_MESSAGE_BUZZERREQUEST_H
