// Generated by gencpp from file transbot_msgs/HeadlightRequest.msg
// DO NOT EDIT!


#ifndef TRANSBOT_MSGS_MESSAGE_HEADLIGHTREQUEST_H
#define TRANSBOT_MSGS_MESSAGE_HEADLIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transbot_msgs
{
template <class ContainerAllocator>
struct HeadlightRequest_
{
  typedef HeadlightRequest_<ContainerAllocator> Type;

  HeadlightRequest_()
    : Headlight(0)  {
    }
  HeadlightRequest_(const ContainerAllocator& _alloc)
    : Headlight(0)  {
  (void)_alloc;
    }



   typedef int32_t _Headlight_type;
  _Headlight_type Headlight;





  typedef boost::shared_ptr< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HeadlightRequest_

typedef ::transbot_msgs::HeadlightRequest_<std::allocator<void> > HeadlightRequest;

typedef boost::shared_ptr< ::transbot_msgs::HeadlightRequest > HeadlightRequestPtr;
typedef boost::shared_ptr< ::transbot_msgs::HeadlightRequest const> HeadlightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transbot_msgs::HeadlightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transbot_msgs::HeadlightRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::HeadlightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Headlight == rhs.Headlight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transbot_msgs::HeadlightRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::HeadlightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3f47b9f75d32f762f5837d105474513";
  }

  static const char* value(const ::transbot_msgs::HeadlightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3f47b9f75d32f76ULL;
  static const uint64_t static_value2 = 0x2f5837d105474513ULL;
};

template<class ContainerAllocator>
struct DataType< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transbot_msgs/HeadlightRequest";
  }

  static const char* value(const ::transbot_msgs::HeadlightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32 Headlight\n"
;
  }

  static const char* value(const ::transbot_msgs::HeadlightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Headlight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadlightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transbot_msgs::HeadlightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transbot_msgs::HeadlightRequest_<ContainerAllocator>& v)
  {
    s << indent << "Headlight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Headlight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSBOT_MSGS_MESSAGE_HEADLIGHTREQUEST_H
