// Generated by gencpp from file transbot_msgs/PatrolRequest.msg
// DO NOT EDIT!


#ifndef TRANSBOT_MSGS_MESSAGE_PATROLREQUEST_H
#define TRANSBOT_MSGS_MESSAGE_PATROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transbot_msgs
{
template <class ContainerAllocator>
struct PatrolRequest_
{
  typedef PatrolRequest_<ContainerAllocator> Type;

  PatrolRequest_()
    : Commond()
    , LineScaling(0.0)
    , RotationScaling(0.0)  {
    }
  PatrolRequest_(const ContainerAllocator& _alloc)
    : Commond(_alloc)
    , LineScaling(0.0)
    , RotationScaling(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Commond_type;
  _Commond_type Commond;

   typedef float _LineScaling_type;
  _LineScaling_type LineScaling;

   typedef float _RotationScaling_type;
  _RotationScaling_type RotationScaling;





  typedef boost::shared_ptr< ::transbot_msgs::PatrolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transbot_msgs::PatrolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolRequest_

typedef ::transbot_msgs::PatrolRequest_<std::allocator<void> > PatrolRequest;

typedef boost::shared_ptr< ::transbot_msgs::PatrolRequest > PatrolRequestPtr;
typedef boost::shared_ptr< ::transbot_msgs::PatrolRequest const> PatrolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transbot_msgs::PatrolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transbot_msgs::PatrolRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Commond == rhs.Commond &&
    lhs.LineScaling == rhs.LineScaling &&
    lhs.RotationScaling == rhs.RotationScaling;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transbot_msgs::PatrolRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::PatrolRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::PatrolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::PatrolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54a9530f2d4ac2afe60a14f4cfd8803a";
  }

  static const char* value(const ::transbot_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54a9530f2d4ac2afULL;
  static const uint64_t static_value2 = 0xe60a14f4cfd8803aULL;
};

template<class ContainerAllocator>
struct DataType< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transbot_msgs/PatrolRequest";
  }

  static const char* value(const ::transbot_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string  Commond\n"
"float32 LineScaling\n"
"float32 RotationScaling\n"
;
  }

  static const char* value(const ::transbot_msgs::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Commond);
      stream.next(m.LineScaling);
      stream.next(m.RotationScaling);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transbot_msgs::PatrolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transbot_msgs::PatrolRequest_<ContainerAllocator>& v)
  {
    s << indent << "Commond: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Commond);
    s << indent << "LineScaling: ";
    Printer<float>::stream(s, indent + "  ", v.LineScaling);
    s << indent << "RotationScaling: ";
    Printer<float>::stream(s, indent + "  ", v.RotationScaling);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSBOT_MSGS_MESSAGE_PATROLREQUEST_H
