// Generated by gencpp from file transbot_msgs/RobotArmRequest.msg
// DO NOT EDIT!


#ifndef TRANSBOT_MSGS_MESSAGE_ROBOTARMREQUEST_H
#define TRANSBOT_MSGS_MESSAGE_ROBOTARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transbot_msgs
{
template <class ContainerAllocator>
struct RobotArmRequest_
{
  typedef RobotArmRequest_<ContainerAllocator> Type;

  RobotArmRequest_()
    : apply()  {
    }
  RobotArmRequest_(const ContainerAllocator& _alloc)
    : apply(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _apply_type;
  _apply_type apply;





  typedef boost::shared_ptr< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotArmRequest_

typedef ::transbot_msgs::RobotArmRequest_<std::allocator<void> > RobotArmRequest;

typedef boost::shared_ptr< ::transbot_msgs::RobotArmRequest > RobotArmRequestPtr;
typedef boost::shared_ptr< ::transbot_msgs::RobotArmRequest const> RobotArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transbot_msgs::RobotArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transbot_msgs::RobotArmRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::RobotArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.apply == rhs.apply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transbot_msgs::RobotArmRequest_<ContainerAllocator1> & lhs, const ::transbot_msgs::RobotArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8e8b3a3b74f38e6cd4cf9904695ae0f";
  }

  static const char* value(const ::transbot_msgs::RobotArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8e8b3a3b74f38e6ULL;
  static const uint64_t static_value2 = 0xcd4cf9904695ae0fULL;
};

template<class ContainerAllocator>
struct DataType< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transbot_msgs/RobotArmRequest";
  }

  static const char* value(const ::transbot_msgs::RobotArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string apply\n"
;
  }

  static const char* value(const ::transbot_msgs::RobotArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.apply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transbot_msgs::RobotArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transbot_msgs::RobotArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "apply: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.apply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSBOT_MSGS_MESSAGE_ROBOTARMREQUEST_H
