export const QUERY_KEY = {
  authMe: ['auth', 'me'],
  roles: ['roles'],
  dashboard: ['statistics', 'dashboard'],
  monthlyStatistics: (month?: string) => ['statistics', 'monthly', month ?? 'current'],
  quarterlyStatistics: (quarter?: string) => ['statistics', 'quarterly', quarter ?? 'current'],
  yearlyStatistics: (year?: string) => ['statistics', 'yearly', year ?? 'current'],
  users: (params: unknown) => ['users', params],
  userDetail: (userId?: number) => ['users', 'detail', userId],
  teams: (params: unknown) => ['teams', params],
  teamDetail: (teamId?: number) => ['teams', 'detail', teamId],
  members: (params: unknown) => ['members', params],
  memberDetail: (memberId?: number) => ['members', 'detail', memberId],
  projects: (params: unknown) => ['projects', params],
  projectDetail: (projectId?: number) => ['projects', 'detail', projectId],
  tasks: (params: unknown) => ['tasks', params],
  taskDetail: (taskId?: number) => ['tasks', 'detail', taskId],
  taskProgress: (taskId?: number) => ['tasks', 'progress', taskId],
  reports: (params: unknown) => ['reports', params],
  reportDetail: (reportId?: number) => ['reports', 'detail', reportId],
  assessments: (params: unknown) => ['assessments', params],
  assessmentDetail: (assessmentId?: number) => ['assessments', 'detail', assessmentId],
  auditLogs: (params: unknown) => ['audit-logs', params],
  auditLogDetail: (logId?: number) => ['audit-logs', 'detail', logId],
} as const
