(cl:defpackage robot_localization-srv
  (:use )
  (:export
   "GETSTATE"
   "<GETSTATE-REQUEST>"
   "GETSTATE-REQUEST"
   "<GETSTATE-RESPONSE>"
   "GETSTATE-RESPONSE"
   "SETDATUM"
   "<SETDATUM-REQUEST>"
   "SETDATUM-REQUEST"
   "<SETDATUM-RESPONSE>"
   "SETDATUM-RESPONSE"
   "SETPOSE"
   "<SETPOSE-REQUEST>"
   "SETPOSE-REQUEST"
   "<SETPOSE-RESPONSE>"
   "SETPOSE-RESPONSE"
  ))

